### ISSUE TITLE
Option to turn off screen 

### ISSUE THREAD

**Issue by boro55** [rgavril/homebridge-xiaomi-air-purifier3#8]
Hi, thanks for your plugin! It'd be great to have the option to turn off screen itself. I keep my purifier on auto 24/7 and there's no point for screen to be on when no one's around.

**Comment by rgavril** [comment]
The only way this can be implemented is trough an additional device(Lightbulb or Switch), since, to my knowledge, there is no native HomeKit support for this functionality.

I don't think is all that useful in the HomeKit context. The only automation scenario I would see is setting the display on/off based on daylight and/or ambient light. Toggling the display on/off with Siri or Home App is just a gimmick.

Until I find I good use scenario for this functionality I don't plan to implement it.

PS: There is a 'Display On/Off' button on the back of the device, why don't use use it to turn off the display ?

**Comment by cece-mae** [comment]
Could it not be a switch like the Mode state (Manual or Automatic), rather than a separate “light switch”? 

The same would apply to the buzzer toggle too

**Comment by rgavril** [comment]
In HomeKit controls like the _Mode_ or _Child Lock_ switches are predefined in HomeKit Accessory Protocol Specification. There are also strict rules on which of this control can a device have. For example an Air Purifier can have those switches but can't have a Brightness slider.

There is no way of adding anything custom, I can only map functionality on what this protocol already offers. 

That is why the only way to get brightness control and on/off switch for the Air Purifier's Display is to implement it trough another device(Lightbulb). That would be a lot of work for a non intuitive and probably not so useful feature for most of the users.

Regarding the buzzer, I don't think the 3/3H models have one.
